# Site settings
title: Sunghyun Jin's Blog+WIKI
url: "https://mcsmonk.github.io/blogwiki"
dnsurl: "https://sunghyunjin.com"
baseurl: "/blogwiki"
description: >
    Sunghyun Jin's Blog and Wiki

# My information
email: mcsmonk@gmail.com
author: Sunghyun Jin
profile: mcsmonk
twitter_username: mcsmonk_shj
github_username: mcsmonk
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: mcsmonk/blogwiki
  repo_id: R_kgDOI2VQEw
  category: Announcements
  category_id: DIC_kwDOI2VQE84CT057

google_analytics:
  ua: G-KTR7QQR16E
#  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
#  client: SAMPLE-VALUE

blame: "https://github.com/mcsmonk/blogwiki/blame/master/_wiki"
edit: "https://github.com/mcsmonk/blogwiki/edit/master/_wiki"
issue: "https://github.com/mcsmonk/blogwiki/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
